#!/bin/bash
echo "Type r for Routes or i for Networking Interfaces:"
read input
if [ "$input" == "r" ]
then
echo "Showing routes:"
route -n
elif [ "$input" == "i' ]
then
echo "Type a networking interface:"
read interface
echo "Showing info of your networking interface $interface:"
ifconfig $interface
else
echo "Invalid Option."
fi

#-c 1 #envia um único pacote ICMP por IP
#grep ttl #filtra a linha output de ping por ttl
#cut -d " " -f 4 #define o espaço como delimitador e seleciona a quarta coluna
#sed #substituição
#. #qualquer caractere
#$ #no final da linha
#// #substituir por nada (remover)
#& #executa o ping em background
